package View;

import Controller.vooController;
import Model.modVoo;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class frmCadastroVoo extends javax.swing.JFrame {

    /**
     * Creates new form frmCadastroVoo
     */
    public frmCadastroVoo() {
        initComponents();
    }

    private void LimparCampos() {
        txtNumeroVoo.setText("");
        txtOrigem.setText("");
        txtDestino.setText("");
        txtQtdLugaresDisponiveis.setText("");
    }

    private Boolean PodeInserir() {
        Boolean podeInserir = false;
        String regexApenasNumeros = "[0-9]+";

        if (txtNumeroVoo.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Informe o número do voo!");
            podeInserir = false;
        } else if (!txtNumeroVoo.getText().matches(regexApenasNumeros)) {
            JOptionPane.showMessageDialog(null, "Informe um número de voo válido!");
            podeInserir = false;
        } else if (txtOrigem.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Informe a origem do voo!");
            podeInserir = false;
        } else if (txtDestino.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Informe o destino do voo!");
            podeInserir = false;
        } else if (txtQtdLugaresDisponiveis.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade de lugares disponíveis !");
            podeInserir = false;
        } else if (!txtQtdLugaresDisponiveis.getText().matches(regexApenasNumeros)) {
            JOptionPane.showMessageDialog(null, "Informe uma quantidade de lugares válida!");
            podeInserir = false;
        } else {
            podeInserir = true;
        }
        return podeInserir;
    }
    

    private void AtribuirValores() {
        if (PodeInserir()) {
            modVoo modVoo = new modVoo();
            modVoo.setNumeroVoo(Integer.valueOf(txtNumeroVoo.getText()));
            modVoo.setOrigem(txtOrigem.getText());
            modVoo.setDestino(txtDestino.getText());
            modVoo.setQtdLugaresDisponiveis(Integer.valueOf(txtQtdLugaresDisponiveis.getText()));
            GravarDados(modVoo);
        }
    }

    private void GravarDados(modVoo voo) {
        try {
            vooController vooController = new vooController();

            if (!vooController.BuscarExistenciaVoo(voo)) {
                vooController.InserirVoo(voo);
                JOptionPane.showMessageDialog(null, "Voo cadastrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Voo de número " + voo.getNumeroVoo() + " já se encontra cadastrado!");
            }
            LimparCampos();
        } catch (Exception ex) {
            //# Trata a exceçõa de violação de chave primária (valor duplicado)
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroVoo = new javax.swing.JLabel();
        txtNumeroVoo = new javax.swing.JTextField();
        txtOrigem = new javax.swing.JTextField();
        lblOrigem = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        txtQtdLugaresDisponiveis = new javax.swing.JTextField();
        lblQtdLugaresDisponiveis = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNumeroVoo.setText("Número Voo: ");

        lblOrigem.setText("Origem:");

        lblDestino.setText("Destino:");

        lblQtdLugaresDisponiveis.setText("Qtd. Lugares Disponíveis:");

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQtdLugaresDisponiveis)
                    .addComponent(lblDestino)
                    .addComponent(lblOrigem)
                    .addComponent(lblNumeroVoo))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroVoo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtOrigem)
                    .addComponent(txtDestino)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravar))
                    .addComponent(txtQtdLugaresDisponiveis))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroVoo)
                    .addComponent(txtNumeroVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigem)
                    .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestino)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdLugaresDisponiveis)
                    .addComponent(txtQtdLugaresDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnLimpar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        AtribuirValores();
    }//GEN-LAST:event_btnGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastroVoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastroVoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastroVoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastroVoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastroVoo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblNumeroVoo;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblQtdLugaresDisponiveis;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNumeroVoo;
    private javax.swing.JTextField txtOrigem;
    private javax.swing.JTextField txtQtdLugaresDisponiveis;
    // End of variables declaration//GEN-END:variables
}
