package View;

/**
 *
 * @author Administrador
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuFerramentas = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroVoo = new javax.swing.JMenuItem();
        menuCadastroReserva = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuConsultaVoo = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastro");

        menuCadastroVoo.setText("Voos");
        menuCadastroVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroVooActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroVoo);

        menuCadastroReserva.setText("Reserva");
        menuCadastroReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroReservaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroReserva);

        menuFerramentas.add(menuCadastro);

        menuConsulta.setText("Consulta");

        menuConsultaVoo.setText("Voo");
        menuConsultaVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaVooActionPerformed(evt);
            }
        });
        menuConsulta.add(menuConsultaVoo);

        menuFerramentas.add(menuConsulta);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuFerramentas.add(menuSair);

        setJMenuBar(menuFerramentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroVooActionPerformed
        new frmCadastroVoo().setVisible(true);
    }//GEN-LAST:event_menuCadastroVooActionPerformed

    private void menuCadastroReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroReservaActionPerformed
        new frmCadastroReserva().setVisible(true);
    }//GEN-LAST:event_menuCadastroReservaActionPerformed

    private void menuConsultaVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaVooActionPerformed
        new frmConsultaVoo().setVisible(true);
    }//GEN-LAST:event_menuConsultaVooActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroReserva;
    private javax.swing.JMenuItem menuCadastroVoo;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuConsultaVoo;
    private javax.swing.JMenuBar menuFerramentas;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
